export type SmallPhotoCardProps = {
	title?: string;
	desc?: string;
	date?: string;
	time?: string;
	height?: number;
	width?: number;
	src?: string;
	imgResolution?: number;
	padding?: number;
	titleSize?: number;
	descriptionSize?: number;
	dateAndTimeSize?: number;
	titleHeight?: number;
	descriptionHeight?: number;
	dateAndTimeHeight?: number;
	pos?: number;
	isClicked?: boolean;
	cardClass?: string;
	titleColor?: string;
};
